import { Block, BlockType } from '@/types';

export type BlockCategory = 'Основные' | 'Продажи' | 'Контент' | 'Системные';

export type BlockPreset = {
  type: BlockType;
  title: string;
  description: string;
  category: BlockCategory;
  preview: string;
  props: Record<string, unknown>;
};

export const blockPresets: BlockPreset[] = [
  {
    type: 'header',
    title: 'Header / Навигация',
    description: 'Логотип, меню, CTA, мобильная адаптация.',
    category: 'Основные',
    preview: 'Navbar',
    props: {
      logo: 'Corshun',
      links: ['Главная', 'Возможности', 'Тарифы', 'Контакты'],
      buttonText: 'Начать',
      backgroundColor: '#050505',
      textColor: '#ffffff',
      buttonBackgroundColor: '#ffffff',
      buttonTextColor: '#000000',
      paddingY: 18,
      paddingX: 32,
      containerWidth: 1240,
      radius: 999,
    },
  },
  {
    type: 'hero',
    title: 'Premium Hero',
    description: 'Большой hero с фоном, overlay, CTA и крупной типографикой.',
    category: 'Основные',
    preview: 'Hero',
    props: {
      eyebrow: 'Corshun Studio',
      title: 'Launch a website that feels premium',
      subtitle:
        'Создавай выразительные сайты с крупной типографикой, сильной визуальной подачей и редактированием прямо на странице.',
      buttonText: 'Начать проект',
      buttonUrl: '#contact',
      secondaryButtonText: 'Смотреть демо',
      secondaryButtonUrl: '#demo',
      layout: 'center',
      height: 92,
      headingSize: 88,
      subtitleSize: 22,
      backgroundColor: '#050505',
      textColor: '#ffffff',
      backgroundImageUrl: '',
      imageUrl: '',
      overlayColor: '#000000',
      overlayOpacity: 42,
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      buttonStyle: 'pill',
      buttonBackgroundColor: '#ffffff',
      buttonTextColor: '#000000',
      secondaryButtonBackgroundColor: 'transparent',
      secondaryButtonTextColor: '#ffffff',
      paddingY: 120,
      paddingX: 32,
      align: 'center',
      radius: 0,
      containerWidth: 1240,
    },
  },
  {
    type: 'features',
    title: 'Features Cards',
    description: 'Карточки преимуществ.',
    category: 'Контент',
    preview: 'Cards',
    props: {
      title: 'Почему выбирают нас',
      items: ['Быстрый запуск', 'Визуальный редактор', 'Готовые блоки'],
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 1180,
    },
  },
  {
    type: 'logos',
    title: 'Logos',
    description: 'Полоса логотипов клиентов или партнеров.',
    category: 'Контент',
    preview: 'Logos',
    props: {
      title: 'Нам доверяют',
      logos: ['Google', 'Stripe', 'Notion', 'Figma', 'Linear'],
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 70,
      paddingX: 32,
      align: 'center',
      containerWidth: 1180,
    },
  },
  {
    type: 'stats',
    title: 'Stats',
    description: 'Цифры, достижения, метрики.',
    category: 'Контент',
    preview: 'Stats',
    props: {
      title: 'Результаты в цифрах',
      items: ['10k+ сайтов', '2 мин запуск', '99% uptime'],
      backgroundColor: '#050505',
      textColor: '#ffffff',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 1180,
    },
  },
  {
    type: 'testimonials',
    title: 'Отзывы',
    description: 'Отзывы клиентов.',
    category: 'Контент',
    preview: 'Reviews',
    props: {
      title: 'Что говорят клиенты',
      items: [
        'Запустили лендинг за вечер.',
        'Редактор реально проще, чем ожидали.',
        'Красиво выглядит без дизайнера.',
      ],
      backgroundColor: '#f6f6f6',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 1180,
    },
  },
  {
    type: 'faq',
    title: 'FAQ',
    description: 'Вопросы и ответы.',
    category: 'Контент',
    preview: 'FAQ',
    props: {
      title: 'Частые вопросы',
      items: [
        'Можно подключить домен?',
        'Можно собирать заявки?',
        'Можно редактировать без кода?',
      ],
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 24,
      containerWidth: 900,
    },
  },
  {
    type: 'pricing',
    title: 'Pricing',
    description: 'Цена, описание и CTA.',
    category: 'Продажи',
    preview: 'Price',
    props: {
      title: 'Простой тариф',
      price: '1990 ₽/мес',
      description: 'Всё нужное для запуска и роста проекта.',
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 1120,
    },
  },
  {
    type: 'cta',
    title: 'CTA',
    description: 'Финальный призыв к действию.',
    category: 'Продажи',
    preview: 'CTA',
    props: {
      title: 'Готовы запустить сайт?',
      buttonText: 'Оставить заявку',
      backgroundColor: '#050505',
      textColor: '#ffffff',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 32,
      containerWidth: 1180,
    },
  },
  {
    type: 'contact',
    title: 'Форма заявки',
    description: 'Форма сохраняет заявки в Supabase.',
    category: 'Продажи',
    preview: 'Form',
    props: {
      title: 'Оставьте заявку',
      subtitle: 'Мы свяжемся с вами в ближайшее время.',
      buttonText: 'Отправить',
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 760,
    },
  },
  {
    type: 'gallery',
    title: 'Gallery',
    description: 'Сетка изображений.',
    category: 'Контент',
    preview: 'Images',
    props: {
      title: 'Selected works',
      images: [],
      backgroundColor: '#ffffff',
      textColor: '#111111',
      paddingY: 96,
      paddingX: 32,
      align: 'center',
      radius: 28,
      containerWidth: 1180,
    },
  },
  {
    type: 'footer',
    title: 'Footer Advanced',
    description: 'Футер с колонками и ссылками.',
    category: 'Системные',
    preview: 'Footer',
    props: {
      brand: 'Corshun',
      description: 'Создавай сайты с высоты.',
      columns: ['Продукт', 'Компания', 'Поддержка'],
      links: ['Блоки', 'Тарифы', 'Домены', 'Контакты', 'Документы', 'Помощь'],
      copyright: '© 2026 Corshun. Все права защищены.',
      backgroundColor: '#050505',
      textColor: '#ffffff',
      paddingY: 70,
      paddingX: 32,
      align: 'left',
      radius: 0,
      containerWidth: 1180,
    },
  },
];

export function createBlockFromPreset(preset: BlockPreset): Block {
  return {
    id: crypto.randomUUID(),
    type: preset.type,
    props: JSON.parse(JSON.stringify(preset.props)),
  };
}